FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    pandas pyarrow pyyaml plotly pillow \
    streamlit

COPY config.yaml .
COPY dashboard/ ./dashboard/
COPY data/reference_data.parquet ./data/
COPY data/simulated/ ./data/simulated/

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "dashboard/app.py", \
     "--server.headless=true", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.baseUrlPath=dashboard"]
